# Generated by Django 5.0.4 on 2024-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delivery_time', models.IntegerField()),
                ('cuisine_type', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
