# Generated by Django 5.0.4 on 2024-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
