# Generated by Django 5.0.4 on 2024-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.PositiveIntegerField(),
        ),
    ]
