# Generated by Django 5.0.4 on 2024-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menuitem_image_url_alter_restaurants_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
