# Generated by Django 5.0.4 on 2024-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='restaurants_name_e810f2_idx'),
        ),
    ]
