# Generated by Django 5.0.4 on 2024-05-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_image_url_alter_restaurants_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_pics'),
        ),
    ]
