# Generated by Django 5.0.4 on 2024-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurants_image_url_restaurants_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dishes_pics'),
        ),
    ]
