# Generated by Django 5.0.4 on 2024-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='street_address',
            field=models.CharField(default='Default Street Address', max_length=255),
            preserve_default=False,
        ),
    ]
