# Generated by Django 5.0.4 on 2024-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_deliveryaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='street_address',
            field=models.CharField(default='Default Street Address', max_length=255),
        ),
    ]
