# Generated by Django 5.0.4 on 2024-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_deliveryaddress_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='address_label',
            field=models.CharField(default='Temporary Label', max_length=100),
            preserve_default=False,
        ),
    ]
