# Generated by Django 5.0.4 on 2024-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deliveryaddress_address_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
